// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered writing improvement and hashtag suggestion flow.
 *
 * - improveWritingAndAddHashtags - A function that enhances post writing and adds relevant hashtags.
 * - ImproveWritingAndAddHashtagsInput - The input type for the improveWritingAndAddHashtags function.
 * - ImproveWritingAndAddHashtagsOutput - The return type for the improveWritingAndAddHashtags function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ImproveWritingAndAddHashtagsInputSchema = z.object({
  text: z.string().describe('The text content of the social media post.'),
  platform: z
    .string()
    .optional()
    .describe('The platform for the post (e.g., Facebook, Instagram, X).'),
});
export type ImproveWritingAndAddHashtagsInput = z.infer<typeof ImproveWritingAndAddHashtagsInputSchema>;

const ImproveWritingAndAddHashtagsOutputSchema = z.object({
  improvedText: z.string().describe('The improved text content for the post.'),
  hashtags: z.string().describe('Relevant hashtags for the post.'),
});
export type ImproveWritingAndAddHashtagsOutput = z.infer<typeof ImproveWritingAndAddHashtagsOutputSchema>;

export async function improveWritingAndAddHashtags(
  input: ImproveWritingAndAddHashtagsInput
): Promise<ImproveWritingAndAddHashtagsOutput> {
  return improveWritingAndAddHashtagsFlow(input);
}

const improveWritingAndAddHashtagsPrompt = ai.definePrompt({
  name: 'improveWritingAndAddHashtagsPrompt',
  input: {schema: ImproveWritingAndAddHashtagsInputSchema},
  output: {schema: ImproveWritingAndAddHashtagsOutputSchema},
  prompt: `You are a social media expert. Improve the writing of the following post and suggest relevant hashtags for the given platform.

Post Text: {{{text}}}
Platform: {{{platform}}}

Improved Text:
Hashtags:`,
});

const improveWritingAndAddHashtagsFlow = ai.defineFlow(
  {
    name: 'improveWritingAndAddHashtagsFlow',
    inputSchema: ImproveWritingAndAddHashtagsInputSchema,
    outputSchema: ImproveWritingAndAddHashtagsOutputSchema,
  },
  async input => {
    const {output} = await improveWritingAndAddHashtagsPrompt(input);
    return output!;
  }
);
